FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema mínimas
RUN pip install --no-cache-dir --upgrade pip


# Requisitos de la API
COPY src/api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Código
COPY src/api/ /app/

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app", "--workers", "2", "--threads", "4"]

